name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: contruir imagen en docker
        run: make build
      - name: run image docker
        run: make run
      - name: quitar la imagen
        run: make rm
      - name: borrar la imagen
        run: make rmi
